### ISSUE TITLE
Parity plots legend should be outside the plot area

### ISSUE THREAD

**Issue by galibar98** [ReactionMechanismGenerator/ARC#629]
**Is your feature request related to a problem? Please describe.**
Yes, the legend is hiding parts of the plot. 
An example image is attached:
[thermo_parity_plots.pdf](https://github.com/ReactionMechanismGenerator/ARC/files/11089181/thermo_parity_plots.pdf)

**Describe the solution you'd like**
Move the legend under or outside the plot area.

**Comment by kfir4444** [comment]
Thanks @galibar98, here is some code that could be useful:
https://stackoverflow.com/questions/4700614/how-to-put-the-legend-outside-the-plot

**Comment by kfir4444** [comment]
Hey @galibar98,
Please take a look at [PR#646](https://github.com/ReactionMechanismGenerator/ARC/pull/646), this should solve this issue.

**Comment by alongd** [comment]
Reopening this issue, the legend is still not fixed, it is often being cut outside the image:
![image](https://github.com/ReactionMechanismGenerator/ARC/assets/16158262/7e757233-3cf4-4a7e-ab79-54b5ec3efc53)

**Comment by alongd** [comment]
fixed by https://github.com/ReactionMechanismGenerator/ARC/pull/669
